# Generated by Django 5.2.8 on 2025-12-08 07:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bukuId', models.CharField(max_length=50, verbose_name='Buku ID')),
                ('judul', models.CharField(max_length=250, verbose_name='Judul')),
                ('isbn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ISBN')),
                ('tahunTerbit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tahun Terbit')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_buku')),
            ],
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendidikanID', models.CharField(max_length=50, verbose_name='Pendidikan ID')),
                ('jenjang', models.CharField(max_length=50, verbose_name='Jenjang Pendidikan')),
                ('namasingkatan', models.CharField(max_length=50, verbose_name='Singkatan')),
            ],
        ),
        migrations.CreateModel(
            name='Penerbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penerbitId', models.CharField(max_length=50, verbose_name='Penerbit ID')),
                ('namapenerbit', models.CharField(max_length=200, verbose_name='Nama Penerbit')),
            ],
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penulisId', models.CharField(max_length=50, verbose_name='Penulis ID')),
                ('namapenulis', models.CharField(max_length=200, verbose_name='Nama Penulis')),
                ('jk', models.CharField(blank=True, choices=[('PRIA', 'PRIA'), ('WANITA', 'WANITA')], max_length=50, null=True, verbose_name='Jenis Kelamin')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_penulis')),
            ],
        ),
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sekolahId', models.CharField(max_length=50, verbose_name='Sekolah ID')),
                ('namasekolah', models.CharField(max_length=200, verbose_name='Nama Sekolah')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('1', 'Admin'), ('2', 'Anggota')], default='1', max_length=1, verbose_name='Tipe User')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendidikan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pendidikan', verbose_name='Pendidikan')),
                ('penulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.penulis', verbose_name='Penulis')),
                ('sekolah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.sekolah', verbose_name='Sekolah')),
            ],
        ),
        migrations.CreateModel(
            name='SumberDayaManusia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=50, verbose_name='No. Induk Kepegawaian')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('jk', models.CharField(blank=True, choices=[('PRIA', 'PRIA'), ('WANITA', 'WANITA')], max_length=50, null=True, verbose_name='Jenis Kelamin')),
                ('nohp', models.CharField(max_length=50, verbose_name='No.Hp')),
                ('tgllahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('tempatlahir', models.CharField(max_length=200, verbose_name='Tempat Lahir')),
                ('alamat', models.TextField(verbose_name='Alamat')),
                ('pendidikan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pendidikan', verbose_name='Pendidikan')),
            ],
        ),
    ]
