# Generated by Django 5.2.8 on 2025-11-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bukuId', models.CharField(max_length=50, verbose_name='Buku ID')),
                ('judul', models.CharField(max_length=250, verbose_name='Judul')),
                ('isbn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ISBN')),
                ('tahunTerbit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tahun Terbit')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
            ],
        ),
    ]
