# Generated by Django 5.2.8 on 2025-11-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penulisId', models.CharField(max_length=50, verbose_name='Penulis ID')),
                ('namapenulis', models.CharField(max_length=50, verbose_name='Nama Penulis')),
            ],
        ),
    ]
