# Generated by Django 5.2.8 on 2025-12-16 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeminjamanBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField(verbose_name='Tanggal Pinjam')),
                ('tanggal_batas_peminjaman', models.DateField(verbose_name='Tanggal Berakhir')),
                ('tanggal_pengembalian', models.DateField(verbose_name='Tanggal Pengembalian')),
                ('jumlah_buku', models.IntegerField(verbose_name='Jumlah Buku')),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku', verbose_name='Buku')),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nama')),
            ],
        ),
    ]
