# Generated by Django 5.2.8 on 2025-12-16 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_peminjamanbuku'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjamanbuku',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peminjamanbuku',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='peminjamanbuku',
            name='jumlah_buku',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Buku'),
        ),
        migrations.AlterField(
            model_name='peminjamanbuku',
            name='tanggal_pengembalian',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Pengembalian'),
        ),
    ]
