# Generated by Django 5.2.8 on 2025-11-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_penulis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penerbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penerbitId', models.CharField(max_length=50, verbose_name='Penerbit ID')),
                ('namapenerbit', models.CharField(max_length=50, verbose_name='Nama Penerbit')),
            ],
        ),
    ]
