# Generated by Django 5.2.8 on 2025-12-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_peminjamanbuku_created_at_peminjamanbuku_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='stok',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stok Buku'),
        ),
    ]
