# Generated by Django 5.2.8 on 2025-11-20 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_penerbit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendidikanID', models.CharField(max_length=50, verbose_name='Pendidikan ID')),
                ('jenjang', models.CharField(max_length=50, verbose_name='Jenjang Pendidikan')),
                ('namasingkatan', models.CharField(max_length=50, verbose_name='Singkatan')),
            ],
        ),
        migrations.AddField(
            model_name='penulis',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='penulis',
            name='jk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='penerbit',
            name='namapenerbit',
            field=models.CharField(max_length=200, verbose_name='Nama Penerbit'),
        ),
        migrations.AlterField(
            model_name='penulis',
            name='namapenulis',
            field=models.CharField(max_length=200, verbose_name='Nama Penulis'),
        ),
        migrations.AddField(
            model_name='penulis',
            name='pendidikan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pendidikan', verbose_name='Pendidikan'),
        ),
    ]
