# Generated by Django 5.2.8 on 2025-11-20 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_pendidikan_penulis_instagram_penulis_jk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penulis',
            name='pendidikan',
        ),
        migrations.AlterField(
            model_name='penulis',
            name='jk',
            field=models.CharField(blank=True, choices=[('PRIA', 'PRIA'), ('WANITA', 'WANITA')], max_length=50, null=True, verbose_name='Jenis Kelamin'),
        ),
        migrations.CreateModel(
            name='HistoryPendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendidikan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pendidikan', verbose_name='Pendidikan')),
            ],
        ),
    ]
