# Generated by Django 5.2.8 on 2025-12-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_buku_stok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjamanbuku',
            name='jumlah_buku',
        ),
        migrations.AddField(
            model_name='peminjamanbuku',
            name='status',
            field=models.CharField(blank=True, choices=[('Pinjam', 'Pinjam'), ('Kembali', 'Kembali')], max_length=50, null=True, verbose_name='Status Peminjaman'),
        ),
    ]
