# Generated by Django 5.2.8 on 2025-11-20 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0005_remove_penulis_pendidikan_alter_penulis_jk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypendidikan',
            name='penulis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.penulis', verbose_name='Penulis'),
        ),
    ]
